name: Create Release on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit messages and descriptions
        id: get_commit_info
        run: |
          MERGE_COMMIT_HASH=$(git log --merges --first-parent -n 1 --pretty=format:"%H" main)
          
          COMMIT_MESSAGES=$(git rev-list --format=%B ${MERGE_COMMIT_HASH}^..${MERGE_COMMIT_HASH} | grep -v '^$')
          echo "::set-output name=commit_messages::${COMMIT_MESSAGES}"

          COMMIT_DESCRIPTIONS=$(git rev-list --format=%s ${MERGE_COMMIT_HASH}^..${MERGE_COMMIT_HASH} | grep -v '^$')
          echo "::set-output name=commit_descriptions::${COMMIT_DESCRIPTIONS}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Specify the tag for the release
          release_name: ${{ steps.get_commit_info.outputs.commit_messages }}  # Title based on commit messages
          body: |
            ${{ steps.get_commit_info.outputs.commit_descriptions }}  # Body based on commit descriptions
