name: Create Release on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get commit information
        id: commit_info
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          echo "::set-output name=commit_message::${COMMIT_MESSAGE}"

          COMMIT_DESCRIPTION=$(git log --format=%s -n 1 ${{ github.sha }})
          echo "::set-output name=commit_description::${COMMIT_DESCRIPTION}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Specify the tag for the release
          release_name: ${{ steps.commit_info.outputs.commit_message }}  # Title based on commit message
          body: ${{ steps.commit_info.outputs.commit_description }}  # Body based on commit description
